spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hsgg
    username: hsgguser
    password: secret

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

app:
  learning-materials-dir: data
